export const GET_TODO_LIST = 'GET_TODO_LIST';
export const SAVE_INPUT_VALUE = 'SAVE_INPUT_VALUE';
export const DELETE_INPUT_VALUE = 'DELETE_INPUT_VALUE';
export const MAKE_AN_ITEM_ACTIVE = 'MAKE_AN_ITEM_ACTIVE';
export const CLEAR_INPUT_VALUE = 'CLEAR_INPUT_VALUE';
